### PR TITLE
Fixing issue with the count() calls containing the < 1 check.

### PR DESCRIPTION
**Pull request by joshbrw**
There is quite a major issue where it checks the config key's existence, but the `< 1` is within the `count()` call.

Sorry for all of the line spacing changes - my editor automatically conforms to PSR-2.

### CODE REVIEW

**Comment by joshbrw** [comment]
Will resolve the conflicts now

**Comment by joshbrw** [comment]
@alexpechkarev I've just realised there's `\PostcodeAnywhere\PostcodeAnywhere` and `\PostcodeAnywhere\php\PostcodeAnywhere` - what's the difference?

**Comment by joshbrw** [comment]
Oh I see, \php\PostcodeAnywhere is for tests - that's odd as normally tests would test the actual class, but if you could give the PR a quick check over I can't see it causing any issues by merging.

**Comment by alexpechkarev** [comment]
Thanks @joshbrw, changes have been merged now.

**Pull request merged**
